HOME_URL = "https://www.google.com"
BOOKMARKS_FILE = "cache//quilix_bookmarks.json"
HISTORY_FILE = "cache//quilix_history.json"
SETTINGS_FILE = "cache//quilix_settings.json"
SESSION_FILE = "cache//quilix_session.json"
NOTES_FILE = "cache//quilix_notes.json"
DARK_STYLE = "styles//dark_mode.css"