repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: (version.txt|CHANGELOG.md|requirements.txt)
      - id: end-of-file-fixer
        exclude: (\.pre-commit-config\.yaml|\.releaserc\.yaml|.*\.yml|.*\.yaml|CHANGELOG\.md|version\.txt|requirements.txt)  # Добавьте requirements.txt
      - id: check-yaml
        exclude: (version.txt|CHANGELOG.md|requirements.txt)
      - id: check-added-large-files
        exclude: (version.txt|CHANGELOG.md|requirements.txt)

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^core/

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [ --config=pyproject.toml ]
        files: ^core/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [ --config=pyproject.toml ]
        files: ^core/