name: CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12', '3.13' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting tools
        run: pip install black isort flake8 mypy pydocstyle
        continue-on-error: true

      - name: Run black
        run: black --check core/
        continue-on-error: true
      - name: Run isort
        run: isort --check-only core/
        continue-on-error: true
      - name: Run flake8
        run: flake8 core/
        continue-on-error: true
      - name: Run mypy
        run: mypy core/
        continue-on-error: true
      - name: Run pydocstyle
        run: pydocstyle core/
        continue-on-error: true