name: Pylint
on: [ push, pull_request ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint on core/
        run: |
          find core/ -name "*.py" -exec pylint {} +
