name: Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine spaceworld
          pip install python-semantic-release[github]

      - name: Get next version
        id: get_version
        run: |
          NEXT_VERSION=$(semantic-release version --print)
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in config
        run: |
          python update_version.py ${{ steps.get_version.outputs.next_version }}

      - name: Build package
        run: python -m build

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          semantic-release publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/